version: "3.7"

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./src:/project/src:cached
      - static:/project/static
      - media:/project/media
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  swapi:
    build:
      context: https://github.com/sleeske/swapi.git
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - api-data:/api/data:cached
    ports:
      - "8001:8001"
    depends_on:
      - swapi-boostrap

  swapi-boostrap:
    build:
      context: https://github.com/sleeske/swapi.git
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py migrate && make load_data"
    volumes:
      - api-data:/api/data:cached

volumes:
  pg-data:
  static:
  media:
  api-data:
